# Generated by Django 3.1.4 on 2021-02-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_book', models.CharField(max_length=100)),
                ('Author_of_book', models.CharField(max_length=100)),
                ('Subjects', models.CharField(choices=[('NULL', 'Not Declared'), ('EE_101', 'Basic Electrical Enginering'), ('MA_111', 'Engineering Maths1'), ('HS_101', 'Communication Skills'), ('ME_102', 'Engineering Workshop'), ('CY_101', 'Engineering Chemistry'), ('MS_101', 'Materials Science '), ('CS_101', 'Computer Programming'), ('ME_101', 'Engineering Graphics'), ('PH_101', 'Engineering Physics'), ('PH_101', 'Applied Mechanics'), ('EC_101', 'Basic Electronics Engineering'), ('MA_121', 'Engineering Mathematics2')], default='NULL', max_length=6)),
            ],
        ),
    ]
